In [2]:
import torch 
import torch.nn as nn 




tril=torch.tril(torch.ones(5,5))


#mask on combination before softmax !!
comb=Q@K.transpose(-2,-1)/mt.sqrt(self.head_size)

masked_comb=comb.masked_fill(tril==0,float("-inf"))

NameError: name 'Q' is not defined

In [2]:
import torch
import torch.nn  as nn

X=torch.randint(100,(100,3))
embed=nn.Embedding(100,20)
embed(X).shape

torch.Size([100, 3, 20])

In [5]:
import tiktoken

gpt2_tokenizer = tiktoken.get_encoding("gpt2")
gpt2_tokenizer.encode(["This is some text","wtf"])
# prints [1212, 318, 617, 2420]

TypeError: expected string or buffer

In [13]:
tril=torch.tril(torch.ones(6,6))

In [18]:
tril.unsqueeze(0).unsqueeze(-1).expand(10,-1,-1,8).shape

torch.Size([10, 6, 6, 8])

In [20]:
(tril.unsqueeze(0).unsqueeze(-1).expand(10,-1,-1,8)==0)[0,:,:,0]

tensor([[False,  True,  True,  True,  True,  True],
        [False, False,  True,  True,  True,  True],
        [False, False, False,  True,  True,  True],
        [False, False, False, False,  True,  True],
        [False, False, False, False, False,  True],
        [False, False, False, False, False, False]])

In [22]:
X=torch.randn(10,6,6,8)
masked=X.masked_fill(tril.unsqueeze(0).unsqueeze(-1).expand(10,-1,-1,8)==0,-float("inf"))

In [29]:
masked[2,:,:,3]

tensor([[-1.1164,    -inf,    -inf,    -inf,    -inf,    -inf],
        [ 0.4114,  0.2675,    -inf,    -inf,    -inf,    -inf],
        [-0.7797,  1.1070,  2.4499,    -inf,    -inf,    -inf],
        [ 2.0326, -1.4321,  0.2987,  0.5092,    -inf,    -inf],
        [-0.7784, -0.0280, -2.0247, -0.2567, -2.0824,    -inf],
        [ 0.1647, -1.0214, -1.6113, -1.8923, -0.1629, -0.3801]])

In [3]:
torch.tril(torch.ones(5,5))

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [9]:
import torch.nn as nn 


nn.Linear(2,3).weight.T

tensor([[-0.2804, -0.0834,  0.5876],
        [-0.4089, -0.1436, -0.3331]], grad_fn=<PermuteBackward0>)